Add debugging and fix inventory

diff --git a/cmk_fastchecker b/cmk_fastchecker
--- a/cmk_fastchecker
+++ b/cmk_fastchecker
@@ -9,26 +9,27 @@ TMP_DIR="/omd/sites/ttnn/tmp/cmk_fastchecker/gunicorn"
 PIDFILE=$TMP_DIR/cmk_fastchecker.pid
 
 start_gunicorn() {
+	[ "$1" == "test" ] || daemon="--daemon"
 	cd $BASE_DIR
 	source venv/bin/activate
+	# --workers $(($(nproc) * 2 + 1)) \
 	gunicorn \
 		--name "cmk_fastchecker" \
 		--bind 127.0.0.1:5001 \
 		--worker-class "gevent" \
-		--workers $(($(nproc) * 2 + 1)) \
+		--workers 1 \
 		--timeout 240 \
-		--max-requests 5000 \
 		--preload \
-		--daemon \
 		--log-file $LOG_DIR/error.log \
 		--access-logfile $LOG_DIR/access.log \
 		--worker-tmp-dir $TMP_DIR \
 		--pid $PIDFILE \
+		$daemon \
 		cmk_fastchecker:app
 }
 
 case "$1" in
-    start)
+    start|test)
  	echo -n 'Starting cmk_fastchecker...'
 	if [ -e "$PIDFILE" ] ; then
 	    PID=$(cat $PIDFILE)
@@ -41,7 +42,7 @@ case "$1" in
 	fi
 
 	# make sure, directories are there (ramdisk!)
-	mkdir -p $TMP_DIR $LOG_DIR && start_gunicorn && echo OK || echo Error
+	mkdir -p $TMP_DIR $LOG_DIR && start_gunicorn "$1" && echo OK || echo Error
     ;;
     stop)
 	echo -n 'Stopping cmk_fastchecker...'
